from datetime import datetime, timezone
from sqlalchemy import Column, Integer, String, Float, DateTime

from src.database.connection import Base

class DetectionHistory(Base):
    """Represents a record of a processed and classified network flow."""
    __tablename__ = "detection_history"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True, nullable=False)
    src_ip = Column(String(50), index=True, nullable=False)
    dst_ip = Column(String(50), index=True, nullable=False)
    src_port = Column(Integer, nullable=False)
    dst_port = Column(Integer, nullable=False)
    protocol = Column(Integer, nullable=False)
    attack_type = Column(String(50), index=True, nullable=False)
    confidence = Column(Float, nullable=False)

    def __repr__(self):
        return (f"<DetectionHistory id={self.id} timestamp={self.timestamp} "
                f"{self.src_ip}:{self.src_port} -> {self.dst_ip}:{self.dst_port} "
                f"proto={self.protocol} attack={self.attack_type} conf={self.confidence:.2f}%>")


class Alert(Base):
    """Represents an active security alert generated by the Alert Engine."""
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True, nullable=False)
    src_ip = Column(String(50), index=True, nullable=False)
    dst_ip = Column(String(50), index=True, nullable=False)
    src_port = Column(Integer, nullable=False)
    dst_port = Column(Integer, nullable=False)
    protocol = Column(Integer, nullable=False)
    attack_type = Column(String(50), index=True, nullable=False)
    confidence = Column(Float, nullable=False)
    message = Column(String(255), nullable=False)

    def __repr__(self):
        return (f"<Alert id={self.id} timestamp={self.timestamp} level=HIGH "
                f"src={self.src_ip}:{self.src_port} dst={self.dst_ip}:{self.dst_port} "
                f"type={self.attack_type} conf={self.confidence:.2f}% msg={self.message}>")
